plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group = "uz.ushodmonov.device_app_info_list"
version = "1.0-SNAPSHOT"

android {
    namespace = "uz.ushodmonov.device_app_info_list"
    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 16
    }
}
